services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --host=0.0.0.0 --port=$PORT app:app
    plan: free
    # Optional: Add environment variables if needed
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
