services:
  - type: web
    name: server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    plan: free
    instances: 1
    autoscale: false
    regions:
      - oregon
    httpPort: 10000
